version: "2.1"

networks:
  cassandra_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
        
services:

#nosql

  # nodetool status to check cluster
  cassandra:
    image: cassandra
    privileged: true
    container_name: cassandra
    tty: true
    ports:
      - "7000:7000"
      - "9042:9042"
      - "7199:7199"
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=10.5.0.200
    networks:                                                                                                                                                                                                                                                                  
      cassandra_net:                                                                                                                                                                                                                                                                  
        ipv4_address: 10.5.0.200
      
  cassandra2:
    image: cassandra
    privileged: true
    container_name: cassandra2
    tty: true
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    depends_on: 
      - "cassandra"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=10.5.0.201
      - CASSANDRA_SEEDS=10.5.0.200
    networks:                                                                                                                                                                                                                                                                  
      cassandra_net:                                                                                                                                                                                                                                                                  
        ipv4_address: 10.5.0.201
        
  cassandra3:
    image: cassandra
    privileged: true
    container_name: cassandra3
    tty: true
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    depends_on: 
      - "cassandra"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=10.5.0.202
      - CASSANDRA_SEEDS=10.5.0.200
    networks:                                                                                                                                                                                                                                                                  
      cassandra_net:                                                                                                                                                                                                                                                                  
        ipv4_address: 10.5.0.202
        
  cassandra4:
    image: cassandra
    privileged: true
    container_name: cassandra4
    tty: true
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    depends_on: 
      - "cassandra"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=10.5.0.203
      - CASSANDRA_SEEDS=10.5.0.200
    networks:                                                                                                                                                                                                                                                                  
      cassandra_net:                                                                                                                                                                                                                                                                  
        ipv4_address: 10.5.0.203
    