version: "2.1"

networks:         
  roachnet:
    driver: bridge
   
services:

  cockroach:
    image: cockroachdb/cockroach
    privileged: true
    container_name: cockroach
    tty: true
    hostname: cockroach 
    command: start --insecure
    ports:
      - "26257:26257" 
      - "8087:8080" 
    environment:
      - HOSTNAME=cockroach 
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    networks: 
      - roachnet
    
  roach2:
    image: cockroachdb/cockroach
    privileged: true
    container_name: roach2
    tty: true
    hostname: roach2 
    command: start --insecure --join=cockroach
    environment:
      - HOSTNAME=roach2
    depends_on:
      - "cockroach"
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    networks: 
      - roachnet
      
  roach3:
    image: cockroachdb/cockroach
    privileged: true
    container_name: roach3
    tty: true
    hostname: roach3
    command: start --insecure --join=cockroach
    environment:
      - HOSTNAME=roach3
    depends_on:
      - "cockroach"
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    networks: 
      - roachnet
      
  roach4:
    image: cockroachdb/cockroach
    privileged: true
    container_name: roach4
    tty: true
    hostname: roach4
    command: start --insecure --join=cockroach
    environment:
      - HOSTNAME=roach4
    depends_on:
      - "cockroach"
    volumes:
      - "../../shared_data:/shared_data"
      - "../../shared_scripts:/shared_scripts"
    networks: 
      - roachnet
